name: intl
description: >
  Contains code to deal with internationalized/localized
  messages, date and number formatting and parsing,
  bi-directional text, and other internationalization issues.
dependencies:
  unittest:
    sdk: unittest
